# ---------- \u7AEF\u53E3\u53F7 ---------------- #
server:
  port: 2001

# ---------- \u670D\u52A1\u540D ---------------- #
spring:
  application:
    name: service-provider-01

# ---------- \u6CE8\u518C\u4E2D\u5FC3 -------------- #
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka



