server:
  port: 8001

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/OBlackCat/spring-cloud-config-repository
          search-paths: config-repository
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
          # username:
          #password:


